4. TO - DO - Task

4.1 Exercise on Functions:

In [ ]:
#Task1

def convert_length(value, unit):
    """
    Converts length between meters and feet.
    :param value: Numeric value to convert
    :param unit: 'm' to convert to feet, 'ft' to convert to meters
    :return: Converted value
    """
    if unit == 'm':
        return value * 3.28084  # meters to feet
    elif unit == 'ft':
        return value / 3.28084  # feet to meters
    else:
        raise ValueError("Invalid length unit")

def convert_weight(value, unit):
    """
    Converts weight between kilograms and pounds.
    :param value: Numeric value to convert
    :param unit: 'kg' to convert to pounds, 'lbs' to convert to kilograms
    :return: Converted value
    """
    if unit == 'kg':
        return value * 2.20462  # kg to lbs
    elif unit == 'lbs':
        return value / 2.20462  # lbs to kg
    else:
        raise ValueError("Invalid weight unit")

def convert_volume(value, unit):
    """
    Converts volume between liters and gallons.
    :param value: Numeric value to convert
    :param unit: 'L' to convert to gallons, 'gal' to convert to liters
    :return: Converted value
    """
    if unit == 'L':
        return value * 0.264172  # liters to gallons
    elif unit == 'gal':
        return value / 0.264172  # gallons to liters
    else:
        raise ValueError("Invalid volume unit")

def main():
    print("Unit Converter")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kilograms <-> pounds)")
    print("3. Volume (liters <-> gallons)")

    try:
        choice = int(input("Choose conversion type (1/2/3): "))
        value = float(input("Enter value to convert: "))

        if choice == 1:
            unit = input("Enter unit (m for meters, ft for feet): ").strip().lower()
            result = convert_length(value, unit)
            print(f"Converted value: {result}")
        elif choice == 2:
            unit = input("Enter unit (kg for kilograms, lbs for pounds): ").strip().lower()
            result = convert_weight(value, unit)
            print(f"Converted value: {result}")
        elif choice == 3:
            unit = input("Enter unit (L for liters, gal for gallons): ").strip().lower()
            result = convert_volume(value, unit)
            print(f"Converted value: {result}")
        else:
            print("Invalid choice. Please select 1, 2, or 3.")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid input.")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()

Unit Converter
1. Length (meters <-> feet)
2. Weight (kilograms <-> pounds)
3. Volume (liters <-> gallons)
Choose conversion type (1/2/3): 2
Enter value to convert: 100
Enter unit (kg for kilograms, lbs for pounds): kg
Converted value: 220.462


In [ ]:
#Task2

def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.
    :param numbers: List of numeric values
    :return: Sum of the numbers
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.
    :param numbers: List of numeric values
    :return: Average of the numbers
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Finds the maximum number in a list.
    :param numbers: List of numeric values
    :return: Maximum value in the list
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum number in a list.
    :param numbers: List of numeric values
    :return: Minimum value in the list
    """
    return min(numbers)

def main():
    print("Mathematical Operations on a List")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Choose an operation (1/2/3/4): "))
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not numbers:
            raise ValueError("The list cannot be empty.")

        if choice == 1:
            result = calculate_sum(numbers)
        elif choice == 2:
            result = calculate_average(numbers)
        elif choice == 3:
            result = find_maximum(numbers)
        elif choice == 4:
            result = find_minimum(numbers)
        else:
            print("Invalid choice. Please select 1, 2, 3, or 4.")
            return

        print(f"Result: {result}")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid input.")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()

Mathematical Operations on a List
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1/2/3/4): 1
Enter numbers separated by spaces: 2 3
Result: 5.0


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:

In [ ]:
def extract_every_other(lst):
    return lst[::2]

# Example usage
print(extract_every_other([1, 2, 3, 4, 5, 6]))


[1, 3, 5]


2. Slice a Sublist:

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

# Example usage
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))


[3, 4, 5]


3. Reverse a List Using Slicing:

In [ ]:
def reverse_list(lst):
    return lst[::-1]

# Example usage
print(reverse_list([1, 2, 3, 4, 5]))


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

# Example usage
print(remove_first_last([1, 2, 3, 4, 5]))

[2, 3, 4]


5. Get the First n Elements:

In [ ]:
def get_first_n(lst, n):
    return lst[:n]

# Example usage
print(get_first_n([1, 2, 3, 4, 5], 3))

[1, 2, 3]


6. Extract Elements from the End:

In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

# Example usage
print(get_last_n([1, 2, 3, 4, 5], 2))


[4, 5]


7. Extract Elements in Reverse Order:

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

# Example usage
print(reverse_skip([1, 2, 3, 4, 5, 6]))


[5, 3, 1]


4.3 Exercise on Nested List:
1. Flatten a Nested List:

In [ ]:
def flatten(lst):
    return [item for sublist in lst for item in sublist]

# Example usage
print(flatten([[1, 2], [3, 4], [5]]))


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

In [ ]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

# Example usage
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print(access_nested_element(nested_list, indices))


6


3. Sum of All Elements in a Nested List:

In [ ]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum nested lists
        else:
            total += item  # Add number to total
    return total

# Example usage
print(sum_nested([[1, 2], [3, [4, 5]], 6]))


21


4. Remove Specific Element from a Nested List:

In [ ]:
def remove_element(lst, elem):
    for i in range(len(lst)):
        if isinstance(lst[i], list):  # If the element is a sublist
            lst[i] = remove_element(lst[i], elem)  # Recursively remove elem from sublist
        else:
            while lst[i] == elem:  # Check if the current element matches elem
                lst.pop(i)  # Remove the element
                break  # Exit loop after removal
    return lst

# Example usage
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(lst, elem))

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

In [ ]:
def find_max(lst):
    max_element = float('-inf')  # Initialize to negative infinity
    for item in lst:
        if isinstance(item, list):  # If item is a sublist, recurse
            max_element = max(max_element, find_max(item))
        else:  # Otherwise, compare the item with the current max
            max_element = max(max_element, item)
    return max_element

# Example usage
print(find_max([[1, 2], [3, [4, 5]], 6]))


6


6. Count Occurrences of an Element in a Nested List:

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, recurse
            count += count_occurrences(item, elem)
        else:  # Otherwise, check if it's equal to the element
            if item == elem:
                count += 1
    return count

# Example usage
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(count_occurrences(lst, elem))

3


7. Flatten a List of Lists of Lists:

In [ ]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recurse
            result.extend(deep_flatten(item))
        else:  # Otherwise, add the item to the result list
            result.append(item)
    return result

# Example usage
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_list))


[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

In [ ]:
def average_nested(lst):
    total = 0
    count = 0

    # Function to recursively calculate the sum and count of elements
    def recursive_sum(lst):
        nonlocal total, count
        for item in lst:
            if isinstance(item, list):
                recursive_sum(item)  # Recurse if the item is a list
            else:
                total += item  # Add item to total
                count += 1  # Increment count

    recursive_sum(lst)
    return total / count if count != 0 else 0  # Avoid division by zero

# Example usage
nested_list = [[1, 2], [3, 4], [5, 6]]
print(average_nested(nested_list))


3.5


10 To - Do - NumPy

10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))

# 3. Return a new array of given shape and type, filled with a fill value (example: fill value = 7)
filled_array = np.full((3, 3), 7)

# 4. Return a new array of zeros with the same shape and type as a given array (using the ones_array as reference)
zeros_like_array = np.zeros_like(ones_array)

# 5. Return a new array of ones with the same shape and type as a given array (using the ones_array as reference)
ones_like_array = np.ones_like(ones_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
new_array = np.array(new_list)

# Output all arrays
print("Empty array 2x2:\n", empty_array)
print("Ones array 4x2:\n", ones_array)
print("Filled array (3x3 filled with 7):\n", filled_array)
print("Zeros-like array:\n", zeros_like_array)
print("Ones-like array:\n", ones_like_array)
print("Converted numpy array from list:\n", new_array)


Empty array 2x2:
 [[1.86071352e-316 0.00000000e+000]
 [6.87124013e-310 2.15296654e-316]]
Ones array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Filled array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros-like array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Ones-like array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Converted numpy array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("Array with values ranging from 10 to 49:\n", arr1)

# 2. Create a 3X3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values ranging from 0 to 8:\n", arr2)

# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 random array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array of size 10 with 5th element replaced with 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr3 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr3[::-1]
print("\nReversed array:\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 matrix with checkerboard pattern:\n", checkerboard)


Array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.04090244 0.55000368 0.3562912  0.2407258  0.65525507 0.10465659
 0.45826513 0.36435021 0.78214532 0.34459194 0.51865586 0.79259295
 0.07230521 0.90664571 0.74561547 0.1727437  0.50232841 0.81844456
 0.10310972 0.5384069  0.51756109 0.4933384  0.62288218 0.65732602
 0.14581266 0.0105577  0.4201848  0.14884203 0.55684331 0.23287222]
Mean of the array: 0.4291418773008593

10x10 random array:
 [[0.42986362 0.79129325 0.44246199 0.47444484 0.46012598 0.18694494
  0.47014714 0.09491833 0.63138498 0.15530761]
 [0.39047267 0.34166933 0.33061278 0.10346412 0.32927783 0.14438228
  0.03257958 0.03335459 0.98507474 0.04125611]
 [0.41081723 0.89264819 0.85980933 0.57469741 0.

Problem - 3: Array Operations:

In [ ]:
import numpy as np

# Define arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)

# 3. Multiply the array with an integer
multiplier = 3  # You can change this value
mult_x = x * multiplier
print("\nMultiplication of x with", multiplier, ":\n", mult_x)

# 4. Find the square of each element of the array
square_x = np.square(x)
print("\nSquare of each element in x:\n", square_x)

# 5. Find the dot product

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# 6. Concatenate x and y along rows and v and w along columns
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))

print("\nConcatenation of x and y along rows:\n", concat_xy)
print("Concatenation of v and w along columns:\n", concat_vw)

# 7. Try concatenating x and v, explain the error if it occurs
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError in concatenating x and v:", e)
    print("Explanation: x is a 2D array of shape (2,2), while v is a 1D array of shape (2,). To concatenate them, we need to reshape v to match the number of columns in x.")


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3 :
 [[ 3  6]
 [ 9 15]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2D array of shape (2,2), while v is a 1D array of shape (2,). To concatenate them, we need to reshape v to match the number of columns in x.


Problem - 4: Matrix Operations:

In [ ]:
import numpy as np

# Define arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^(-1) = I
A_inv = np.linalg.inv(A)  # Find inverse of A
identity_matrix = np.dot(A, A_inv)
print("A * A^(-1) = I:\n", np.round(identity_matrix, decimals=5))

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAB ≠ BA:", not np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("\n(AB)^T = B^T * A^T:", np.array_equal(AB_T, BT_AT))

# Solve system of linear equations using inverse method
# Represent the equations in matrix form AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Solve for X using np.linalg.inv
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("\nSolution for AX = B using inverse method:", X)


A * A^(-1) = I:
 [[1. 0.]
 [0. 1.]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

AB ≠ BA: True

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]

(AB)^T = B^T * A^T: True

Solution for AX = B using inverse method: [ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?

1. Element-wise Addition:

In [ ]:
import numpy as np
import time

# Define lists of size 1,000,000
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

# Measure time for element-wise addition using Python lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise addition using Python lists:", end_time - start_time, "seconds")

# Define NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Measure time for element-wise addition using NumPy arrays
start_time = time.time()
numpy_sum = array1 + array2
end_time = time.time()
print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time, "seconds")


Time taken for element-wise addition using Python lists: 0.22178149223327637 seconds
Time taken for element-wise addition using NumPy arrays: 0.0029103755950927734 seconds


2. Element-wise Multiplication

In [ ]:
import numpy as np
import time

# Define lists of size 1,000,000
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

# Measure time for element-wise addition using Python lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise addition using Python lists:", end_time - start_time, "seconds")

# Define NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Measure time for element-wise addition using NumPy arrays
start_time = time.time()
numpy_sum = array1 + array2
end_time = time.time()
print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time, "seconds")

# Measure time for element-wise multiplication using Python lists
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise multiplication using Python lists:", end_time - start_time, "seconds")

# Measure time for element-wise multiplication using NumPy arrays
start_time = time.time()
numpy_product = array1 * array2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy arrays:", end_time - start_time, "seconds")


Time taken for element-wise addition using Python lists: 0.05084633827209473 seconds
Time taken for element-wise addition using NumPy arrays: 0.005177736282348633 seconds
Time taken for element-wise multiplication using Python lists: 0.10908842086791992 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.0027904510498046875 seconds


3. Dot Product

In [ ]:
import numpy as np
import time

# Define lists of size 1,000,000
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

# Measure time for element-wise addition using Python lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise addition using Python lists:", end_time - start_time, "seconds")

# Define NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Measure time for element-wise addition using NumPy arrays
start_time = time.time()
numpy_sum = array1 + array2
end_time = time.time()
print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time, "seconds")

# Measure time for element-wise multiplication using Python lists
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise multiplication using Python lists:", end_time - start_time, "seconds")

# Measure time for element-wise multiplication using NumPy arrays
start_time = time.time()
numpy_product = array1 * array2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy arrays:", end_time - start_time, "seconds")

# Measure time for dot product using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print("Time taken for dot product using Python lists:", end_time - start_time, "seconds")

# Measure time for dot product using NumPy arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()
print("Time taken for dot product using NumPy arrays:", end_time - start_time, "seconds")



Time taken for element-wise addition using Python lists: 0.04731941223144531 seconds
Time taken for element-wise addition using NumPy arrays: 0.0024504661560058594 seconds
Time taken for element-wise multiplication using Python lists: 0.1107790470123291 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.0014882087707519531 seconds
Time taken for dot product using Python lists: 0.0597994327545166 seconds
Time taken for dot product using NumPy arrays: 0.0019428730010986328 seconds


4. Matrix Multiplication

In [ ]:
import numpy as np
import time

# Define lists of size 1,000,000
size = 1000000
list1 = list(range(size))
list2 = list(range(size))

# Measure time for element-wise addition using Python lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise addition using Python lists:", end_time - start_time, "seconds")

# Define NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Measure time for element-wise addition using NumPy arrays
start_time = time.time()
numpy_sum = array1 + array2
end_time = time.time()
print("Time taken for element-wise addition using NumPy arrays:", end_time - start_time, "seconds")

# Measure time for element-wise multiplication using Python lists
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise multiplication using Python lists:", end_time - start_time, "seconds")

# Measure time for element-wise multiplication using NumPy arrays
start_time = time.time()
numpy_product = array1 * array2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy arrays:", end_time - start_time, "seconds")

# Measure time for dot product using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print("Time taken for dot product using Python lists:", end_time - start_time, "seconds")

# Measure time for dot product using NumPy arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()
print("Time taken for dot product using NumPy arrays:", end_time - start_time, "seconds")

# Define matrices of size 1000x1000
matrix_size = 1000
matrix1 = [[i * j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[j * i for j in range(matrix_size)] for i in range(matrix_size)]

# Measure time for matrix multiplication using Python lists
start_time = time.time()
matrix_result = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]
end_time = time.time()
print("Time taken for matrix multiplication using Python lists:", end_time - start_time, "seconds")

# Define NumPy matrices
np_matrix1 = np.array(matrix1)
p_np_matrix2 = np.array(matrix2)

# Measure time for matrix multiplication using NumPy arrays
start_time = time.time()
np_matrix_result = np.dot(np_matrix1, p_np_matrix2)
end_time = time.time()
print("Time taken for matrix multiplication using NumPy arrays:", end_time - start_time, "seconds")


Time taken for element-wise addition using Python lists: 0.05285978317260742 seconds
Time taken for element-wise addition using NumPy arrays: 0.001680135726928711 seconds
Time taken for element-wise multiplication using Python lists: 0.04939389228820801 seconds
Time taken for element-wise multiplication using NumPy arrays: 0.0018703937530517578 seconds
Time taken for dot product using Python lists: 0.05871224403381348 seconds
Time taken for dot product using NumPy arrays: 0.0010302066802978516 seconds
Time taken for matrix multiplication using Python lists: 102.06483387947083 seconds
Time taken for matrix multiplication using NumPy arrays: 0.8354384899139404 seconds
